name: My first workflow

# trigger
on: 
- push

jobs:
   # name of your job
   my-first-job:
      # runner
      runs-on: ubuntu-latest
      # steps in this job
      steps:
      - name: echo the date
        run: echo "hello, Github Action $(date)"

      - name: echo the git branch
        uses: mscoutermarsh/cowsays-action@master
        with:
         text: "I am on branch ${{ github.base_ref }}"
         color: green
