name: My first workflow

# trigger
on: 
- push

jobs:
   # name of your job
   my-first-job:
      # runner
      runs-on: ubuntu-latest
      # steps in this job
      steps:
      - name: echo the date
        run: "echo hello, Github Action $(date)"

      - name: List before checkout 
        run: ls -l

      - name: checkout source code
        uses: actions/checkout@v3
        with:
            ref: ${{github.base_ref}}

      - name: List directory
        run: ls -l

      - name: echo the git branch
        uses: mscoutermarsh/cowsays-action@master
        with:
         text: ${{secrets.MY_API_KEY}}
         color: green
